### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by vojtajina** [karma-runner/karma-teamcity-reporter#11]
@edjafarov would you like to change the LICENSE to be with your name?

I'm a Google employee and so Karma is owned by Google. I'm changing all the licenses to "Google", which means dealing with CLA and other bullshit. I didn't contribute to this plugin that much - you did it, so I think it would make more sense if we change the license to your name. Let me know what you think.

**Comment by Dignifiedquire** [comment]
Closing this for now as it is pretty outdated
