### ISSUE TITLE
Not all tests report

### ISSUE THREAD

**Issue by aaronjensen** [karma-runner/karma-teamcity-reporter#31]
When running with the teamcity reporter, only about 200 of our 900 tests actually report.  I think they are all running, but karma seems to quit before all output has been flushed. This is true when actually running on TeamCity

One thing I've noticed is that if I run `karma start --single-run` it only shows about 200 testFinisheds, but if I pipe it to anything, including piping to `tee` it reports everything. It seems to be treating tty as different, and this doesn't actually work on TeamCity. I can probably pipe to `tee` just to get it working...

**Comment by aaronjensen** [comment]
This seems to be fixed on master. If you could drop a new release it'd be great :) Thanks!

**Comment by Dignifiedquire** [comment]
Published

**Comment by aaronjensen** [comment]
Thanks!
