### ISSUE TITLE
Incomplete test reporting

### ISSUE THREAD

**Issue by chad-configit** [karma-runner/karma-teamcity-reporter#5]
We are experiencing a problem with test reporting in the TeamCity reporter.

We previously used the junit reporting format which successfully reported 100% of our tests in a consistent fashion. We switched over to the teamcity reporter and started experiencing variation in our test count.

When we check the log we see (for example)

```
[15:23:21]    [DependencyGraphConfig] should be invalid when non-numeric depth
[15:23:21]    [DependencyGraphConfig] ##teamcity[testStarted
```
```
[08:57:24]     [RulesFilter] should toggle filter off
[08:57:24]     [RulesFilter] ##teamcity[t
```
and a more odd looking scenario:
```
[14:59:54]    [WorkItems.UpdateController] Should change the status to Not applicable
[14:59:54]      [Should change the status to Not applicable] ##teamcity[testFinished name='Should change the status to Not applica
```
The point at which it crops the text seems to vary even when running the exact same builds.

My best guess as to what's happening is that the reporter is somehow flushing a line midway through and teamcity, defensively, is not waiting to see if it receives any more and stops the test reporting. This would imply it affects other line-by-line reporters though, so I'm not sure about that.

Our build server is running Windows 2008 and we're using the latest Karma from npm (0.8.5)

Any help or feedback would be appreciated.

**Comment by AlexCuse** [comment]
Is there any chance of this synchronous write fix making it up to NPM?  I have an interesting requirement for my build that necessitates running the agent as the "local system" windows user, which in turn precludes installing the package via git reference.

**Comment by nievebc** [comment]
@kdrvn's fix works for me too. This fix should really get merged- or at least tell us what needs to be done to get it merged and moved into NPM, so that we can send a PR. Please.
